// Recopie a l'identique du bloc `nav:` de l'ancien mkdocs.yml.
//
// DECISION DE MIGRATION — barre laterale EXPLICITE, surtout pas 'autogenerated'.
// 17 fichiers sont publies sans figurer dans la nav (tout guides/, tout projet/,
// operations/b2-cap-exceeded, operations/r2-migration). Ils restent accessibles
// par URL mais invisibles au menu, exactement comme avec MkDocs. Une sidebar
// autogeneree les ferait tous apparaitre d'un coup — ce serait un changement de
// comportement glisse dans une migration qui doit etre neutre.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    { type: 'doc', id: 'index', label: 'Accueil' },
    {
      type: 'category',
      label: 'Architecture',
      link: { type: 'doc', id: 'architecture/index' },
      items: [
        { type: 'doc', id: 'architecture/hardware', label: 'Machines' },
        { type: 'doc', id: 'architecture/os', label: 'Optimisations OS' },
        { type: 'doc', id: 'architecture/reseau', label: 'Reseau actuel' },
        { type: 'doc', id: 'architecture/acces-reseau', label: 'Acces aux services' },
        { type: 'doc', id: 'architecture/reseau-cible', label: 'Reseau cible' },
        { type: 'doc', id: 'architecture/cluster-qdevice', label: 'Cluster qdevice' },
      ],
    },
    {
      type: 'category',
      label: 'Services',
      link: { type: 'doc', id: 'services/index' },
      items: [
        { type: 'doc', id: 'services/homepage', label: 'Homepage (dashboard)' },
        { type: 'doc', id: 'services/traefik', label: 'Traefik' },
        { type: 'doc', id: 'services/authelia', label: 'Authelia (SSO)' },
        { type: 'doc', id: 'services/adguard', label: 'AdGuard Home' },
        { type: 'doc', id: 'services/vaultwarden', label: 'Vaultwarden' },
        { type: 'doc', id: 'services/grafana', label: 'Grafana (logs)' },
        { type: 'doc', id: 'services/alloy-loki-ha', label: 'Alloy + Loki HA' },
        { type: 'doc', id: 'services/claude-remote', label: 'Claude Remote Control' },
        { type: 'doc', id: 'services/firefly', label: 'Firefly III (finances)' },
        { type: 'doc', id: 'services/zomboid', label: 'Project Zomboid' },
      ],
    },
    {
      type: 'category',
      label: 'Securite',
      link: { type: 'doc', id: 'securite/index' },
      items: [
        { type: 'doc', id: 'securite/politique', label: 'Politique' },
        { type: 'doc', id: 'securite/comptes', label: 'Comptes et service accounts' },
        { type: 'doc', id: 'securite/hardening', label: 'Hardening' },
        { type: 'doc', id: 'securite/roadmap', label: 'Roadmap' },
        { type: 'doc', id: 'securite/yubikey-age-setup', label: 'YubiKey age setup' },
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      link: { type: 'doc', id: 'operations/index' },
      items: [
        { type: 'doc', id: 'operations/monitoring', label: 'Monitoring' },
        { type: 'doc', id: 'operations/notif-hygiene', label: 'Notif hygiene' },
        { type: 'doc', id: 'operations/backups', label: 'Backups' },
        { type: 'doc', id: 'operations/break-glass', label: 'Break-glass' },
        { type: 'doc', id: 'operations/depannage', label: 'Depannage' },
        { type: 'doc', id: 'operations/incidents-recurrents', label: 'Incidents recurrents' },
        { type: 'doc', id: 'operations/forgejo-acces-urgence', label: 'Forgejo (acces urgence)' },
        { type: 'doc', id: 'operations/dr-drill-scenario-1', label: 'DR drill scenario 1' },
      ],
    },
    {
      type: 'category',
      label: 'Mentions',
      items: [
        { type: 'doc', id: 'confidentialite', label: 'Confidentialite' },
        { type: 'doc', id: 'conditions', label: "Conditions d'utilisation" },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'guides/index' },
      items: [
        { type: 'doc', id: 'guides/ajouter-service', label: 'Ajouter un service' },
        { type: 'doc', id: 'guides/proxmox-zimaboard', label: 'Proxmox sur ZimaBoard' },
        { type: 'doc', id: 'guides/tls', label: 'TLS et certificats' },
      ],
    },
    {
      type: 'category',
      label: 'Projet',
      link: { type: 'doc', id: 'projet/index' },
      items: [
        { type: 'doc', id: 'projet/decisions', label: 'Decisions techniques' },
        { type: 'doc', id: 'projet/roadmap', label: 'Roadmap (4 phases hardware)' },
        { type: 'doc', id: 'projet/sucre', label: 'sucre (SRE perso, arrete)' },
        { type: 'doc', id: 'projet/sucre-observability', label: 'sucre — observabilite' },
        { type: 'doc', id: 'projet/about', label: 'A propos' },
        {
          // Artefacts DATES : specs, plans, rapports, instantanes, post-mortems.
          // On ne les reecrit pas, on les date. Ordre chronologique inverse : le
          // plus recent en premier, c'est ce qu'on relit.
          type: 'category',
          label: 'Journal',
          collapsed: true,
          items: [
            { type: 'doc', id: 'projet/journal/2026-08-26-audit-fraicheur-doc', label: '2026-08-26 — Audit de fraicheur de la doc' },
            { type: 'doc', id: 'projet/journal/2026-08-25-migration-docusaurus', label: '2026-08-25 — Migration MkDocs vers Docusaurus' },
            { type: 'doc', id: 'projet/journal/2026-08-15-forgejo-source-de-verite', label: '2026-08-15 — Forgejo source de verite' },
            { type: 'doc', id: 'projet/journal/2026-08-15-boite-a-outils-technique', label: '2026-08-15 — Boite a outils technique' },
            { type: 'doc', id: 'projet/journal/2026-08-04-homepage-themes-fonds-design', label: '2026-08-04 — Homepage : themes et fonds' },
            { type: 'doc', id: 'projet/journal/2026-08-03-homepage-refonte-design', label: '2026-08-03 — Homepage : refonte' },
            { type: 'doc', id: 'projet/journal/2026-06-11-fiabilisation-drill-restauration', label: '2026-06-11 — Fiabilisation du drill' },
            { type: 'doc', id: 'projet/journal/2026-05-11-migration-r2', label: '2026-05-11 — Migration vers Cloudflare R2' },
            { type: 'doc', id: 'projet/journal/2026-05-11-roadmap-consolidee', label: '2026-05-11 — Roadmap consolidee (instantane)' },
            { type: 'doc', id: 'projet/journal/2026-05-10-b2-cap-exceeded', label: '2026-05-10 — Quota B2 depasse' },
            { type: 'doc', id: 'projet/journal/2026-04-19-egress-phase2', label: '2026-04-19 — Egress firewall phase 2 (plan)' },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
